### ISSUE TITLE
Question about schemas in this project.

### ISSUE THREAD

**Issue by lgertel** [delvedor/monoliths-always-pay-their-debts#2]
Great job here. I'm currently starting to upgrade a monolithic fastify application to a microservices implementation. This tutorial is a fantastic starting point. Thanks for that @delvedor .

Reading this code, a question that comes into my mind is that why the schema files are all the same between the microservices?

Thanks!

**Comment by delvedor** [comment]
Hi, thank you!

> Reading this code, a question that comes into my mind is that why the schema files are all the same between the microservices?

No reason, I was too lazy to remove the useless schemas, so I just copy-pasted the file without updating it :)
