### ISSUE TITLE
Question about patterns!

### ISSUE THREAD

**Issue by lgertel** [delvedor/monoliths-always-pay-their-debts#3]
Hello @delvedor, hope you're doing well.

As I'm using your knowledge to refactor my existing application, there is one question regarding the right way to communicate between services call.
For exemple:
How to do the right implementation if the post service has to request an api from user for example. Should the post call gateway or the service directly with inject?

Thanks!

**Comment by delvedor** [comment]
You can definitely use `inject` to call your services without adding the overhead of a standard HTTP call. The only problem I see is if you use it to communicate between services that at some point in the future you will split.
`inject` works only at the instance level, it does not touch the network layer, even if the API is the same.
